const LOAD_DATA = '[HOME] LOAD DATA '
const LOAD_DATA_SUCCESS = '[HOME] LOAD DATA SUCCESS'
const LOAD_DATA_FAILED = '[HOME] LOAD DATA FAILED'

const LOAD_DATA_VEHICLES = '[HOME] LOAD DATA VEHICLES '
const LOAD_DATA_VEHICLES_SUCCESS = '[HOME] LOAD DATA VEHICLES SUCCESS'
const LOAD_DATA_VEHICLES_FAILED = '[HOME] LOAD DATA VEHICLES FAILED'

const REMOVE_DATA = '[HOME] REMOVE DATA'
const SET_SEARCH = '[HOME] SET SEARCH'
const SET_SELECTED_PERSON = '[HOME] SET SELECTED_PERSON'

export default {
  LOAD_DATA,
  LOAD_DATA_SUCCESS,
  LOAD_DATA_FAILED,
  LOAD_DATA_VEHICLES,
  LOAD_DATA_VEHICLES_SUCCESS,
  LOAD_DATA_VEHICLES_FAILED,
  REMOVE_DATA,
  SET_SEARCH,
  SET_SELECTED_PERSON
}
