export const LOAD_DATA = '[HOME] LOAD DATA ';
export const LOAD_DATA_SUCCESS = '[HOME] LOAD DATA SUCCESS';
export const LOAD_DATA_FAILED = '[HOME] LOAD DATA FAILED';

export const REMOVE_DATA = '[HOME] REMOVE DATA';
export const SET_LOADING = '[VEHICLE] SET LOADING';

export default {
  LOAD_DATA,
  LOAD_DATA_SUCCESS,
  LOAD_DATA_FAILED,
  REMOVE_DATA,
  SET_LOADING,

}
