export const LOAD_DATA = '[HOME] LOAD DATA ';
export const LOAD_DATA_SUCCESS = '[HOME] LOAD DATA SUCCESS';
export const LOAD_DATA_FAILED = '[HOME] LOAD DATA FAILED';

export const REMOVE_DATA = '[HOME] REMOVE DATA';
export const LOADING_DATA = '[VEHICLE] LOADING DATA';

export default {
  LOAD_DATA,
  LOAD_DATA_SUCCESS,
  LOAD_DATA_FAILED
}
