const LOAD_DATA = '[HOME] LOAD DATA ';
const LOAD_DATA_SUCCESS = '[HOME] LOAD DATA SUCCESS';
const LOAD_DATA_FAILED = '[HOME] LOAD DATA FAILED';

const REMOVE_DATA = '[HOME] REMOVE DATA';
const SET_LOADING = '[VEHICLE] SET LOADING';

export default {
  LOAD_DATA,
  LOAD_DATA_SUCCESS,
  LOAD_DATA_FAILED,
  REMOVE_DATA,
  SET_LOADING
}
